### PR TITLE
Mastery Excercise

### PR DESCRIPTION
**Pull request by priyakamesh**

### CODE REVIEW

**Comment by dmserrano** [comment]
Your code looks good, however a couple of requirements from the directions aren't met:

1. While your tree function accepts the tree object, the function that builds the tree should be the one accepting the object (the tabFun function).

2. The input field validation doesn't quite seem to be working. If one of the input fields is empty and I press the enter key, it still runs the build tree function, when it should show an alert warning that one field is empty.

Let me know if I can help!

**Comment by priyakamesh** [comment]
Hello Dominic,
I am sorry to not meeting the requirements in my code.
I have made changes in my code according to the requirements you listed.
Can I commit the new changes in the dev branch which I was using to do
previous commits or shall I create a new branch and push it.



Thanks,
Krishnapriya.

**Comment by dmserrano** [comment]
Yes, committing and pushing to the dev branch will work.

**Comment by dmserrano** [comment]
Looks good 👍  you are good to push up

**Pull request merged**
